{{- if and .Values.monitoring.enabled (ne (len .Values.monitoring.rules) 0) .Values.monitoring.operator }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
spec:
  groups:
  - name: postgresql.rules
    rules:
{{ toYaml .Values.monitoring.rules | indent 4 }}
{{- end }}
