{{- if .Values.consul.templates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microfleet.fullname" . }}-consul-templates
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
data:
{{ toYaml .Values.consul.templates | indent 2 }}
{{- end }}