apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testsuit.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "testsuit.name" . }}
    helm.sh/chart: {{ include "testsuit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data: {}