###
# fly -t sl sp -c pipeline.yml -p helm-charts
###
resource_types:
- name: telegram-notification
  type: docker-image
  source:
    repository: w32blaster/concourse-telegram-notifier

resources:
- name: notify
  type: telegram-notification
  source:
    bot_token: ((tg-bot-token))
- name: sources
  type: git
  source:
    uri: https://github.com/makeomatic/helm-charts.git
    # paths: ["/charts/*"]

jobs:
- name: generate-charts
  plan:
    - get: sources
      trigger: true
    - task: update-charts
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: makeomatic/k8s-ci
            tag: "12102018"
        inputs:
          - name: sources
        run:
          path: sh
          args:
          - -exc
          - |
            . configure-gcloud
            ./sources/scripts/upload.sh
      params:
        CLOUDSDK_API_KEY: ((gcp-deployer-key))
        CLOUDSDK_COMPUTE_ZONE: ((gcp-zone))
        CLOUDSDK_CORE_PROJECT: ((gcp-project))
        KUBERNETES_CLUSTER: ((gcp-cluster-name))
      on_failure:
        put: notify
        params:
          chat_id: ((tg-chat-id))
          text: Can't update helm charts ($ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME)