apiVersion: makeomatic.ca/v1alpha1
kind: Micro
metadata:
  name: nginx-test
spec:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
  service:
    ports:
    - name: http
      port: 8080
