apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "redis-cluster.fullname" . }}-trib
  labels:
    app: {{ template "redis-cluster.name" . }}
    chart: {{ template "redis-cluster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ template "redis-cluster.name" . }}
        chart: {{ template "redis-cluster.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Never
      containers:
      - name: create-shards
        image: sgrio/redis-trib
        # get redis instances ips and create shards
        command:
          - sh
          - -c
          - HOSTS=`nslookup {{ template "redis-cluster.fullname" . }} | tail -n +3 | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | sed 's/.*/&:6379/' | xargs` && yes yes | ./redis-trib.rb create --replicas 0 $HOSTS
      