replicaCount: 2

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

healtcheck:
  enabled: false
  path: /

ingress:
  enabled: false
  host: chart-example.local
  path: /
  tls: true
  annotations: {}
    # kubernetes.io/tls-acme: "true"

resources: {}
  
nodeSelector: {}

tolerations: []

antiAffinity: "soft"

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1

extraVars: {}
# - name: TCMALLOC_AGGRESSIVE_DECOMMIT
#   value: "true"

config:
  enabled: false
  name: ms-configs
  path: /configs