fullnameOverride: ""
replicaCount: 2

nameOverride: ""
serviceAccountName: ""

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

health:
  enabled: true
  path: /generic/health
  port: http

http:
  enabled: false
  service:
    nameOverride: "" # ability to rewrite default service name
    type: ClusterIP
    port: 8080
  ingress:
    host: "" # do not create ingress if empty
    path: /
    createTls: true
    annotations: {}

grpc:
  enabled: false
  service:
    nameOverride: ""
    type: ClusterIP
    port: 8081
  ingress:
    host: ""
    path: /
    createTls: true
    annotations: {}

resources: {}
  
nodeSelector: {}

tolerations: []

antiAffinity: "soft"

# https://kubernetes.io/docs/tasks/run-application/configure-pdb/
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1

extraVars: {}
  # - name: TCMALLOC_AGGRESSIVE_DECOMMIT
  #   value: "true"

configuration: {}
# configuration:
#   config.js: |-
#     module.exports = {
#       logger: {
#         defaultLogger: true,
#         debug: true,
#         streams: {
#           sentry: {
#             dns: '...',
#           },
#         },
#       }
#     }