# Default values for redis-cluster.
# helm install ./redis-cluster -n test --wait

# amount of instances should not be lower than 3
# replicas is not supporting yet
mastersCount: 3

image:
  repository: redis
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

affinity: {}

nodeSelector: {}

tolerations: []

antiAffinity: "soft"

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1