apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redis-cluster.fullname" . }}
  labels:
    app: {{ template "redis-cluster.name" . }}
    chart: {{ template "redis-cluster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no