{{ if eq .Values.proxy.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ template "rethinkdb.fullname" . }}-proxy"
  labels:
    app: "{{ template "rethinkdb.name" . }}-proxy"
    chart: {{ include "rethinkdb.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  serviceName: "{{ template "rethinkdb.fullname" . }}-proxy"
  updateStrategy:
{{ toYaml .Values.proxy.updateStrategy | indent 4 }}
  podManagementPolicy: {{ .Values.proxy.podManagementPolicy }}
  selector:
    matchLabels:
      app: "{{ template "rethinkdb.name" . }}-proxy"
      chart: {{ include "rethinkdb.chart" . }}
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      name: "{{ template "rethinkdb.fullname" . }}-proxy"
      labels:
        app: "{{ template "rethinkdb.name" . }}-proxy"
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ template "rethinkdb.chart" . }}"
      annotations:
      {{- if .Values.proxy.podAnnotations }}
{{ toYaml .Values.proxy.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.proxy.affinity }}
      affinity:
{{ tpl .Values.proxy.affinity . | indent 8 | trim }}
      {{- end }}
      {{- if .Values.proxy.tolerations }}
      tolerations:
{{ toYaml .Values.proxy.tolerations | indent 6 }}
      {{- end }}
      serviceAccountName: {{ include "rethinkdb.serviceAccountName" . }}
      initContainers:
        - name: "{{ template "rethinkdb.name" . }}-init"
          image: "alpine:3.7"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: "config"
              mountPath: "/config"
            - name: "entrypoint"
              mountPath: "/entrypoint"
          command:
            - sh
            - -c
            - >
              cp /config/entrypoint.sh /entrypoint && chmod +x /entrypoint/entrypoint.sh && ls -alF /entrypoint
      containers:
        - name: "{{ template "rethinkdb.name" . }}-proxy"
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: cluster
              containerPort: {{ .Values.ports.cluster }}
            - name: driver
              containerPort: {{ .Values.ports.driver }}
            - name: admin
              containerPort: {{ .Values.ports.admin }}
          command:
            - "/usr/local/bin/dumb-init"
          args:
            - "/entrypoint/entrypoint.sh"
            - "--bind"
            - "all"
            {{- if .Values.proxy.driverTLS.enabled }}
            - "--driver-tls-key"
            - "/secrets/driver-key.pem"
            - "--driver-tls-cert"
            - "/secrets/driver-cert.pem"
            {{- end }}
          volumeMounts:
            - name: "secrets"
              mountPath: "/secrets"
            - name: "entrypoint"
              mountPath: "/entrypoint"
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: "{{ include "rethinkdb.fullname" . }}-cluster"
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rethinkdb.fullname" . }}
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
{{ toYaml .Values.proxy.resources | indent 12 }}

      volumes:
        - name: entrypoint
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "rethinkdb.fullname" . }}-config
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ template "rethinkdb.fullname" . }}
{{ end }}
