apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rethinkdb.fullname" . }}-config
  labels:
    app: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
data:
  {{- range $path, $name :=  .Files.Glob  "files/**" }}
{{ $path | trimPrefix "files/" | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
  {{- end }}
