{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "microfleet.serviceAccountName" . }}
  labels:
    app: {{ template "microfleet.fullname" . }}
    chart: {{ template "microfleet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
