{{ $host := .Values.gateway.host }}
{{ $httpsRedirect := .Values.gateway.httpsRedirect }}
{{- if and .Values.meshEnabled $host }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microfleet.name" . }}
    helm.sh/chart: {{ include "microfleet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    istio: ingressgateway
  servers:
  {{- range .Values.gateway.ports }}
  {{ $protocol := default "http" .protocol }}
    - hosts:
      - {{ $host }}
      port:
        name: {{ .name }}
        protocol: {{ $protocol }}
        number: {{ .port }}
    {{- if eq $protocol "https" }}
      tls:
        mode: SIMPLE
        httpsRedirect: {{ $httpsRedirect }}
        serverCertificate: /etc/istio/ingressgateway-certs/{{ $host }}.crt
        privateKey: /etc/istio/ingressgateway-certs/{{ $host }}.key
    {{- end }}
  {{- end }}
{{- end }}