{{ $gateway := .Values.gateway }}
{{- if and .Values.meshEnabled $gateway.host }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microfleet.name" . }}
    helm.sh/chart: {{ include "microfleet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    istio: ingressgateway
  servers:
  {{- range .Values.gateway.ports }}
  {{ $protocol := default "http" .protocol }}
    - hosts:
      - {{ $gateway.host }}
      port:
        name: {{ .name }}
        protocol: {{ $protocol }}
        number: {{ .port }}
    {{- if and (eq $protocol "http") $gateway.httpsRedirect }}
      tls:
        httpsRedirect: true
    {{- end }}
    {{- if eq $protocol "https" }}
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/{{ default "tls" $gateway.customCrtName }}.crt
        privateKey: /etc/istio/ingressgateway-certs/{{ default "tls" $gateway.customCrtName }}.key
    {{- end }}
  {{- end }}
{{- end }}