{{- if or .Values.service.ports .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    ### human-readable labels for queries and discovery (ex.: prometheus-operator)
    app: {{ include "microfleet.name" . }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
    
    ### labels recommended by documentation (backward compatibility mostly)
    app.kubernetes.io/name: {{ include "microfleet.name" . }}
    helm.sh/chart: {{ include "microfleet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      protocol: {{ default "TCP" .protocol }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: {{ .Values.monitoring.port }}
      protocol: TCP
  {{- end }}
  selector:
    app: {{ include "microfleet.name" . }}
    release: {{ .Release.Name }}
{{- end }}