{{- if .Values.entrypoint.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "microfleet.name" . }}
    helm.sh/chart: {{ include "microfleet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.entrypoint.serviceType }}
  ports:
  {{- range .Values.entrypoint.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      protocol: {{ default "TCP" .protocol }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "microfleet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}