{{- if or .Values.service.ports .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app: {{ include "microfleet.name" . }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      protocol: {{ default "TCP" .protocol }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.port }}
      targetPort: {{ .Values.monitoring.port }}
      protocol: TCP
  {{- end }}
  selector:
    app: {{ include "microfleet.name" . }}
    release: {{ .Release.Name }}
{{- end }}