# NOTE: short host name is taken from _rule_ namespace, not from _service_ namespace
{{- if and .Values.meshEnabled .Values.service.ports }}
{{ $serviceName := include "microfleet.fullname" . }}
{{ $defaultServicePort := (index .Values.service.ports 0).port }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "microfleet.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "microfleet.name" . }}
    helm.sh/chart: {{ include "microfleet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  gateways:
  - {{ default (include "microfleet.fullname" .) .Values.gateway.name }}
  hosts:
  - {{ .Values.gateway.host }}
  http:
  {{- range .Values.gateway.ports }}
  - match:
    - port: {{ .port }}
    route:
    - destination:
        host: {{ $serviceName }}
        port:
          number: {{ default $defaultServicePort .targetPort }}
  {{- end }}
{{- end }}