apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: micros.makeomatic.ca
spec:
  group: makeomatic.ca
  names:
    kind: Micro
    listKind: MicroList
    plural: micros
    singular: micro
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
