apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-operator
# TODO: granulate role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - services
#   - endpoints
#   - persistentvolumeclaims
#   - events
#   - configmaps
#   - secrets
#   verbs:
#   - '*'
# - apiGroups:
#   - ""
#   resources:
#   - namespaces
#   verbs:
#   - get
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   - replicasets
#   - statefulsets
#   verbs:
#   - '*'
# - apiGroups:
#   - monitoring.coreos.com
#   resources:
#   - servicemonitors
#   verbs:
#   - get
#   - create
# - apiGroups:
#   - apps
#   resourceNames:
#   - fleet
#   resources:
#   - deployments/finalizers
#   verbs:
#   - update
# - apiGroups:
#   - makeomatic.ca
#   resources:
#   - '*'
#   verbs:
#   - '*'
