{{ required "A valid image is required" (or .Values.image.tag .Values.image.repository) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
spec:
  podManagementPolicy: Parallel
  serviceName: ""
  replicas: {{ .Values.replicaCount }}
{{- if .Values.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.toolchain.config.files }}
        checksum/config-files: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.toolchain.consul.templates }}
        checksum/config-consul: {{ include (print $.Template.BasePath "/consul.templates.yaml") . | sha256sum }}
        {{- end }}
        sidecar.istio.io/inject: "{{ .Values.toolchain.istio.enabled }}"
        {{- if .Values.toolchain.fluentbit.enabled }}
        fluentbit.io/enabled: "true"
        {{- end }}
        {{- if .Values.toolchain.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.toolchain.monitoring.port }}"
        prometheus.io/scheme: "http"
        prometheus.io/path: "{{ .Values.toolchain.monitoring.path }}"
        {{- end }}
        {{- if .Values.toolchain.istio.enabled }}
        kiali.io/runtimes: "{{ .Values.toolchain.istio.kiali.runtime }}"
        {{- end }}
      labels:
        app: {{ .Release.Name }}
        version: {{ .Values.image.tag | quote }}
    spec:
      {{- if eq .Values.serviceAccountName "" }}
      automountServiceAccountToken: false
      {{- else }}
      serviceAccountName: "{{ .Values.serviceAccountName }}"
      {{- end }}
      {{- if or .Values.initContainers .Values.toolchain.consul.templates }}
      initContainers:
      {{- if .Values.toolchain.consul.templates }}
      - name: consul-template
        image: hashicorp/consul-template:alpine
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumeMounts:
        - name: consul-template
          mountPath: /template
        - name: consul-config
          mountPath: /config
        command:
          - sh
          - -ec
          - |
            consul-template -consul-addr="$NODE_IP:8500" -once \
            {{- range $filename, $content := .Values.toolchain.consul.templates }}
              -template "/template/{{ $filename }}:/config/{{ $filename }}" \
            {{- end }}

            cat /config/*
      {{- end }}
      {{- if .Values.initContainers }}
{{ toYaml .Values.initContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        {{- if .Values.env }}
{{ toYaml .Values.env | indent 10 }}
        {{- end }}
        {{- if or .Values.volumeMounts .Values.toolchain.consul.templates .Values.toolchain.config.files }}
          volumeMounts:
          {{- if .Values.toolchain.config.files }}
          - name: config
            mountPath: {{ .Values.toolchain.config.path }}
          {{- end }}
          {{- if .Values.toolchain.consul.templates }}
          - name: consul-config
            mountPath: {{ .Values.toolchain.consul.path }}
          {{- end }}
          {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 10 }}
          {{- end }}
          {{- end }}
          {{- if .Values.command }}
          command:
{{ toYaml .Values.command | indent 10 }}
          {{- end }}
          {{- if .Values.args }}
          args:
{{ toYaml .Values.args | indent 10 }}
          {{- end }}
          {{- if .Values.service.ports }}
          ports:
          {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ default .port .targetPort }}
              protocol: {{ default "TCP" .protocol }}
          {{- end }}
          {{- end }}

          {{- if .Values.health.checkLiveness }}
          livenessProbe:
{{ toYaml .Values.health.liveness | indent 12 -}}
          {{- end }}
          {{- if .Values.health.checkReadiness }}
          readinessProbe:
{{ toYaml .Values.health.readiness | indent 12 -}}
          {{- end }}

          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}

    {{- if .Values.affinity }}
      affinity:
        {{ tpl .Values.affinity . | indent 8 | trim }}
    {{- end }}
      {{- if or .Values.volumes .Values.toolchain.consul.templates .Values.toolchain.config.files }}
      volumes:
      {{- if .Values.toolchain.consul.templates }}
      - name: consul-template
        configMap:
          name: {{ include "microfleet.fullname" . }}-consul-templates
      - name: consul-config
        emptyDir: {}
      {{- end }}
      {{- if .Values.toolchain.config.files }}
      - name: config
        configMap:
          name: {{ include "microfleet.fullname" . }}-config
      {{- end }}
      {{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 6 }}
      {{- end }}
      {{- end }}
