kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "clickhouse.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    helm.sh/chart: {{ include "clickhouse.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ toYaml .Values.config | indent 2 }}
