apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-direct
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    helm.sh/chart: {{ include "clickhouse.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.tcpPort }}
      targetPort: native
      protocol: TCP
      name: native
  selector:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
