# helm template . --name test -f debug.yaml -x templates/cronjobs.yaml
# helm install -n test ./charts/service -f ./charts/service/debug.yaml --dry-run --debug
# kubectl logs -l app.kubernetes.io/instance=test -c consul-template
fullnameOverride: test
replicaCount: 1

image:
  repository: qwe

service:
  http:
    nameOverride: ""
    type: LoadBalancer
    port: 3000
    ingress:
      host: some.domain.tld
      tls: true # create tls certificate for specified ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"