apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-testjob
  labels:
    app.kubernetes.io/name: service
    helm.sh/chart: service-1.0.0
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Tiller
spec:
  concurrencyPolicy: Forbid
  schedule: "@daily"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 86400
      completition:
      parallelism: 1
      template:
        spec:
          automountServiceAccountToken: false
          containers:
          - name: testjob
            image: busybox
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
