{{- $name := include "ms.name" . -}}
{{- $fullName := include "ms.fullname" . -}}
{{- $chart := include "ms.chart" . -}}
{{- $release := .Release.Name -}}
{{- $service := .Release.Service -}}
{{- range $svcName, $svc := .Values.service }}

{{- $defaultName := printf "%s-%s" $fullName $svcName -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.nameOverride | default $defaultName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $release }}
    app.kubernetes.io/managed-by: {{ $service }}
    component: microservice
spec:
  type: {{ $svc.type }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svcName }}
      protocol: TCP
      name: {{ $svcName }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $release }}
{{- end }}