{{- $name := include "ms.name" . -}}
{{- $fullName := include "ms.fullname" . -}}
{{- $chart := include "ms.chart" . -}}
{{- $release := .Release.Name -}}
{{- $service := .Release.Service -}}

{{- range $svcName, $svc := .Values.service }}

{{- $defaultName := printf "%s-%s" $fullName $svcName -}}
{{- $displayName := $svc.nameOverride | default $defaultName -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $displayName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $release }}
    app.kubernetes.io/managed-by: {{ $service }}
    component: microservice
spec:
  type: {{ $svc.type }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svcName }}
      protocol: TCP
      name: {{ $svcName }}
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $release }}

{{- $ing := $svc.ingress }}
{{- if $ing.host }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $displayName }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $release }}
    app.kubernetes.io/managed-by: {{ $service }}
  annotations:
{{- with $ing.annotations }}
{{ toYaml $ing.annotations | indent 4 }}
{{- end }}
spec:
{{- if $ing.tls }}
  tls:
    - hosts:
        - {{ $ing.host }}
      secretName: {{ $svcName }}-tls
{{- end }}
  rules:
    - host: {{ $ing.host }}
      http:
        paths:
          - path: {{ $ing.path }}
            backend:
              serviceName: {{ $displayName }}
              servicePort: {{ $svcName }}
{{- end }}

{{- end }}